### PR TITLE
Breaking code into modules

### PR DESCRIPTION
**Pull request by jerinjohnk**
Please test this once before publishing.
I started by improving the index.js, but I felt code snippets were scattered around, so I started grouping them to move them to their files if needed.
I was wondering if I should replace `RESULT_CATEGORIES` with

```
const RESULT_CATEGORIES = {
  fullJs: "supported",
  native: "notSupported",
  supported: "supported",
  notSupported: "notSupported",
  notFound: "notFound",
} as const;
```
Replacing all const string with `RESULT_CATEGORIES.supported`, etc., but felt it would reduce readability more.

### CODE REVIEW

**Comment by jerinjohnk** [comment]
Hi @arochedy , did you get time to review this PR

**Comment by arochedy** [comment]
Hi,

Sorry for the delay I just check it and it's ok.

You are now maintener of the project (tell me if is not working) ;)

**Comment by arochedy** [comment]
for this :

const RESULT_CATEGORIES = {
  fullJs: "supported",
  native: "notSupported",
  supported: "supported",
  notSupported: "notSupported",
  notFound: "notFound",
} as const;

I think you can use it. It will not reduce readibility I think

**Comment by jerinjohnk** [comment]
> Hi,
> 
> Sorry for the delay I just check it and it's ok.
> 
> You are now maintener of the project (tell me if is not working) ;)

It's always better to review and merge PR's. 
In case I miss out on something and to avoid any form of malicious code.

**Pull request merged**
